#!/bin/bash

AWS_ACCESS_KEY_ID=DEFAULT_AWS_ACCESS_KEY_ID
export AWS_ACCESS_KEY_ID

AWS_SECRET_ACCESS_KEY=DEFAULT_AWS_SECRET_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY

AWS_REGION=localhost
export AWS_REGION

DYNAMODB_ENDPOINT=http://localhost:8000
export DYNAMODB_ENDPOINT

serverless offline start