AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resource definitions for the Movies RESTful API

Resources:
  CreateMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: handlers/create_movie.create
      CodeUri: .
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: Movies
      Events:
        Api:
          Type: Api
          Properties:
            Path: /v1/api/movies
            Method: POST

  GetMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: handlers/get_movie.get
      CodeUri: .
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: Movies
      Events:
        Api:
          Type: Api
          Properties:
            Path: /v1/api/movies/{id}
            Method: GET

  UpdateMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: handlers/update_movie.update
      CodeUri: .
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: Movies
      Events:
        Api:
          Type: Api
          Properties:
            Path: /v1/api/movies/{id}
            Method: PUT

  DeleteMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: handlers/delete_movie.delete
      CodeUri: .
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: Movies
      Events:
        Api:
          Type: Api
          Properties:
            Path: /v1/api/movies/{id}
            Method: DELETE

  ProcessMoviesStream:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: handlers/movies_stream.process
      Policies: 
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: MoviesReplica
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - MoviesTable
                - StreamArn
            BatchSize: 10
            StartingPosition: TRIM_HORIZON

  MoviesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Movies
      AttributeDefinitions:
        - AttributeName: movie-id
          AttributeType: S
      KeySchema:
        - AttributeName: movie-id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  MoviesReplicaTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: MoviesReplica
      AttributeDefinitions:
        - AttributeName: movie-id
          AttributeType: S
      KeySchema:
        - AttributeName: movie-id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
